### ISSUE TITLE
npy文件不存在

### ISSUE THREAD

**Issue by vangjin** [dvlab-research/GFS-Seg#3]
您好，由于一些路径的设置读不到的问题，我不得不使用python train.py命令来进行评估，但是为什么他会报错如下：
```
[val] Creating new lists and will save to **./saved_npy/val_split_0_seed_321_shot_10_np_data_list.npy** and **./saved_npy/val_split_0
_seed_321_shot_10_np_supp_list.npy**Totally 1449 samples in val set.
Starting Checking image&label pair val list...
100%|###########################################################################################| 1449/1449 [00:05<00:00, 242.36it/s]
Checking Pretrain image&label pair val list 0 done!
All 1016 pairs in base classes.
Checking image&label pair val list done!
All 433 pairs in novel classes.
All 1449 pairs in base + novel classes.
Traceback (most recent call last):
  File "train.py", line 500, in <module>
    main()
  File "train.py", line 93, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "train.py", line 215, in main_worker
    data_split=args.data_split, use_coco=args.use_coco)
  File "/wjin21/GFS-Seg/util/dataset.py", line 206, in __init__
    np.save(path_np_data_list, np_data_list)
  File "<__array_function__ internals>", line 6, in save
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 530, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: './saved_npy/val_split_0_seed_321_shot_10_np_data_list.npy'
```
这个npy文件可以自己手动创建一个吗？
但是sh文件中好像也没有创建这个文件的命令

**Comment by tianzhuotao** [comment]
Hi! Thanks for your attention.

You may need to create the directory on your own, and run the train.sh that will automatically generate new .npy files.

More details can be found in the dataset processing scripts.

Please check again the data paths before yielding new npy files, otherwise empty or invalid paths will be saved.

**Comment by vangjin** [comment]
Thanks for your answer.
Now,i can run the code, but i met a new problem, when i want to evaluation only, i have imported the pre-trained network model and set the correct data path,but the result of my running only can get  5 classses's accuracy and the final accuracy has a certain gap between the paper,i want to ask how to get all classes's  accuracy.
The running result is as follows：
![3MV320K86H 5{GQGJXQXVXF](https://user-images.githubusercontent.com/92430995/187852988-c19961f1-cd57-417e-8a3f-fa5a73d4bd2a.png)
