### ISSUE TITLE
Retraining (without pre-trained models)

### ISSUE THREAD

**Issue by cty21995** [dvlab-research/GFS-Seg#4]
I want to know how much epoch will converge for retraining without loading the pre training model and only loading the ImageNet pre trained backbones. Why do I still have the following effects when I train more than 10 epochs (My batch_size is 2.).Is the model prone to fall into local values? 
![Uploading 30cbe4d4a2b510257a3f7a37271b53b.jpg…]()
![cd8ae738a1ad2fac60b9a26695f1a72](https://user-images.githubusercontent.com/107451143/187476334-98795d1d-87cd-4e04-a940-a302203eaeef.jpg)

**Comment by tianzhuotao** [comment]
Thank you for your interest!

In my experiments, models will converge normally with our default configuration files. 

Please check your dataset preparation by directly testing the well-trained models we provide in this repo to see whether you can get the correct performance.

**Comment by cty21995** [comment]
It is my equipment problem. The data set preparation is correct. Now I have obtained the converged model. Thank you for your reply.
