### ISSUE TITLE
Question about Data split

### ISSUE THREAD

**Issue by Pixie8888** [dvlab-research/GFS-Seg#5]
Hi,
Thanks for releasing the code. I have a question regarding the data split. It seems you learn all the novel classes in one step. During test, you sample k shots for each novel class in the split. The queries are sampled from the novel classes only, but requires segment both base and novel classes. Is my understanding correct?

**Comment by tianzhuotao** [comment]
"It seems you learn all the novel classes in one step." 

- Yes

"During test, you sample k shots for each novel class in the split. The queries are sampled from the novel classes only, but requires segment both base and novel classes."

- No. Query images are directly taken from the original validation set, and both base and novel classes are required to be identified.

Thank you for being interested in our work.

If you have any further questions please feel free to ask me.

**Comment by tianzhuotao** [comment]
Also, the k-shot support samples used during testing are collected from the train set instead of the validation set. Please refer to https://github.com/dvlab-research/GFS-Seg/blob/master/train.py#L221.

**Comment by Pixie8888** [comment]
thanks
